### ISSUE TITLE
Is the var/let example mixed up?

### ISSUE THREAD

**Issue by prayerslayer** [DrkSephy/es6-cheatsheet#13]
Because I'm pretty sure it is.

**Comment by bulatb** [comment]
Mixed up how?

**Comment by wesleytodd** [comment]
I don't think it is mixed up.  While functionally correct, I think it is a fairly poor example.  Especially for a learning piece.

**Comment by wesleytodd** [comment]
Here is a better example from MDN:

``` javascript
function varTest() {
  var x = 31;
  if (true) {
    var x = 71;  // same variable!
    console.log(x);  // 71
  }
  console.log(x);  // 71
}

function letTest() {
  let x = 31;
  if (true) {
    let x = 71;  // different variable
    console.log(x);  // 71
  }
  console.log(x);  // 31
}
```

**Comment by bulatb** [comment]
The MDN example shows the difference in scoping, but it doesn't show that `let` won't hoist up to the function's scope. The example in the cheatsheet shows that `var` will let you shadow a `var` from an ancestor scope even if the code in which the shadow is declared is never reached. But that's also why it's confusing... but that confusion is also what it tries to show. So I don't know.

Would a comment that explains why `snack` gets undefined address both problems?

**Comment by jaredmcateer** [comment]
Agreed it's not mixed up it's only a little ambiguous as to what's going on.

``` javascript
var snack = 'Meow Mix';

function getFood(food) {
    if (food) {
        var snack = 'Friskies';
        return snack;
    }
    return snack;
}

getFood(false); // undefined
```

With hoising becomes:

``` javascript
var snack = 'Meow Mix';

function getFood(food) {
    var snack = undefined; // <--- hoisted from if statement
    if (food) {
        snack = 'Friskies';
        return snack;
    }
    return snack;
}

getFood(false); // undefined
```

With `let`/`const` variables are not hoisted.

``` javascript
let snack = 'Meow Mix';

function getFood(food) {

    if (food) {
        let snack = 'Friskies'; // <-- doesn't get hoisted, doesn't even get executed since 'food' is false
        return snack;
    }
    // 1. snack variable undefined in this scope
    // 2. Traverses up ancestor tree to find variable
    // 3. Find it in parent/global scope, returns that variable.
    return snack; 
}

getFood(false); // 'Meow Mix'
```

If you want to take the example one step further you could write something like:

``` javascript
let snack = 'Meow Mix';

function getFood(food) {

    if (food) {
        let snack = 'Friskies'; // <-- new snack variable specific to this scope
    }
    // 1. snack variable undefined in this scope, it is not the same as the one in the if statement scope
    // 2. Traverses up ancestor tree to find variable
    // 3. Find it in parent/global scope, returns that variable.
    return snack; 
}

getFood(true); // 'Meow Mix'
```

**Comment by wesleytodd** [comment]
The example @jaredmcateer shows both concepts more clearly.  I would also add similar comments to the var example describing how hoisting works so it is clear that the example is intended to show both scoping and hoisting.

**Comment by prayerslayer** [comment]
Ah, to be honest I missed the inner `snack` variable :see_no_evil: Sorry. All is good.
