### ISSUE TITLE
Named imports is not destructuring

### ISSUE THREAD

**Issue by hyb175** [DrkSephy/es6-cheatsheet#14]
In the importing section you said: 

> We can also use destructuring to import a list of values from a file:
> 
> ``` javascript
> import { sumTwo, sumThree } from 'math/addition'
> ```
> 
> Similar to Python, we have named imports:
> 
> ``` javascript
> import { 
>   sumTwo as addTwoNumbers, 
>   sumThree as sumThreeNumbers
> } from 'math/addition'
> ```

But according to [this](http://www.2ality.com/2014/09/es6-modules-final.html), both are named imports except the second one is using renaming. I think the correct way to use destructuring is when importing the default or wildcard. Like for `'math/addtion'` we would do

``` javascript
import * as addtionUtil from 'math/addtion';
const { sumTwo, sumThree } = addtionUtil;
```

**Comment by hyb175** [comment]
Have a pr [here](https://github.com/DrkSephy/es6-cheatsheet/pull/18)

**Comment by DrkSephy** [comment]
Thanks for pointing this out. I merged your PR :+1:
