### ISSUE TITLE
Preserving newlines in template literals example doesn't yield the same results as ES5 example

### ISSUE THREAD

**Issue by possibilities** [DrkSephy/es6-cheatsheet#22]
Notice the extra whitespace you end up with https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20text%20%3D%20(%0A%20%20%60cat%0A%20%20dog%0A%20%20nickelodeon%60%0A)

**Comment by DrkSephy** [comment]
Good catch. The code should have been this:

``` javascript
let text = ( `
  cat
  dog
  nickelodeon`
)

console.log(text)
```

I'll update the example now. Thanks :+1:

**Comment by possibilities** [comment]
I don't think that's equiv either:

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20text%20%3D%20(%20%60%0A%20%20cat%0A%20%20dog%0A%20%20nickelodeon%60%0A)

**Comment by possibilities** [comment]
My thinking is there's no nice way, have to resort to this, hoping you prove me wrong (:

```
let text = (`
cat
dog
nickelodeon
`)
```

To me the reason that's "not nice" is that if you want to do this in e.g. a function you end up with this:

```
const shows = () => {
  let text = (`
cat
dog
nickelodeon`)
}
```
