### ISSUE TITLE
Converting repository to JavaScript

### ISSUE THREAD

**Issue by LarryBattle** [DrkSephy/es6-cheatsheet#25]
How so?
Reference: https://github.com/DrkSephy/es6-cheatsheet/commit/25e4c8ba2bfc0205bae08ede5dffa51a0e4a4c36#diff-17043324503bc20a641fb90473de9fac

**Comment by DrkSephy** [comment]
By adding a simple JavaScript file to the repository, the language is now set to JavaScript.
