### ISSUE TITLE
Map with keys of any type

### ISSUE THREAD

**Issue by berdario** [DrkSephy/es6-cheatsheet#30]
While technically correct (you can insert them and enumerate through all the values in a Map/Set), "use any type" ignores the fact that you cannot actually query a Map for keys of any type

> The most amazing part of Maps is that we are no longer limited to just using strings. We can now use any type as a key, and it will not be type-casted to a string.
> 
> ```
> let map = new Map([
>     ['name', 'david'],
>     [true, 'false'],
>     [1, 'one'],
>     [{}, 'object'],
>     [function () {}, 'function']
> ]);
> ```

This might give people misconceptions, since it overlooks the fact that EcmaScript doesn't define equality for non-primitive values.

That is `map.get({})` or `map.get(function () {})` will give you back `undefined` (You'd have the same problem with `Array`, `Date` and any other object)

For this reason, people might want to use a library that actually shoulder that burden like:
- http://swannodette.github.io/mori/
- https://facebook.github.io/immutable-js/

(and, as an added bonus, the structures these libs define are immutable)

**Comment by sQu1rr** [comment]
as with any js object {} !== {}. Referential equality
let a = {}; // then a === a
so map.get(a) will work for map.set(a, ...)

**Comment by DrkSephy** [comment]
This is true. I should make a mention that we are no longer limited to strings, but we can only effectively use maps with primitive values. I'll go ahead and update the example to make note of this. Much appreciated! :+1:

**Comment by berdario** [comment]
Uh, good. Thanks for handling this so quickly. :+1: 

In case people might want to nitpick: I tried to be careful in my choice of words:

>  EcmaScript doesn't define equality for non-primitive values

As opposed to equality for non-primitives (by) reference, which is (should be?) well defined, much simpler to implement, but not what people want in most cases. It actually seems like the ES standard doesn't talk about "reference equality" and "value equality", so I don't think that people would get confused if we're not using that terminology... I just felt like I should mention it
