### ISSUE TITLE
Clarify let and const vs var

### ISSUE THREAD

**Issue by joews** [DrkSephy/es6-cheatsheet#33]
The section on `let` and `const` doesn't mention that they are [block scoped](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let#Block_scope_with_let). I think that is the most significant difference to most developers.

Also, saying that `let` and `const` are not hoisted is too simplistic because it does not account for the [Temporal Dead Zone](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/).

In short, accessing block-scoped identifiers before they are defined is a `ReferenceError`:

``` javascript
console.log(x);
let x = "hi";   // ReferenceError: x is not defined
```

This happens even when a matching identifier exists in an outer scope. The inner `x` _is_ effectively hoisted, but the result of accessing it before declaration is an Error, not `undefined`.

``` javascript
let x = "outer";

if (true) {
  console.log(x); // ReferenceError: x is not defined
  let x = "inner";
}
```

**Comment by DrkSephy** [comment]
Thank you for your comments! I went ahead and updated the content based on what you mentioned. I'll hold off on talking about the temporal dead zone, as I feel that the `ReferenceError` example you provided is clear enough (on top of noting that `let` and `const` are block-scoped.)
