### ISSUE TITLE
WeakMap description

### ISSUE THREAD

**Issue by benlesh** [DrkSephy/es6-cheatsheet#34]
WeakMap generally has little to do with classes or privatizing values.

WeakMap in JavaScript is the same as WeakMap in many other languages. It's a Map, essentially a Hash keyed by references to objects, that will GC entries when nothing else holds on to the reference.

It's "weak" because it holds onto the reference "weakly".  [MDN has good documentation on WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)

A use case for WeakMap would be something like storing data associated to a particular DOM element without polluting the DOM itself. If the DOM element is cleaned up, the entry in the WeakMap is GC'ed.

**Comment by maxkueng** [comment]
:+1:

**Comment by DrkSephy** [comment]
Good points. I thought that using WeakMaps for privatizing values might have been somewhat useful. Regarding holding data about DOM elements, I completely agree with you. I'll go ahead and add in a practical example which uses WeakMaps for storing DOM data.
