### ISSUE TITLE
Incorrect description of `let`/`const`

### ISSUE THREAD

**Issue by mathiasbynens** [DrkSephy/es6-cheatsheet#40]
> **Best Practice**: Leave **var** declarations inside of legacy code to denote that it needs to be carefully refactored. When working on a new codebase, use **let** for variables that will change their value over time, and **const** for variables that will be immutable over time.

`const` has nothing to do with immutability. A `const` can still change its value, e.g.:

``` js
const x = {};
x.foo = 42;
```

The difference between `let` and `const` is that [assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators) can be used for `let` but not `const`.

**Comment by DrkSephy** [comment]
You're right, when it comes to objects you can change the value as shown above. I'll go ahead and make the distinction.
