### ISSUE TITLE
Mention fetch in the example about promises?

### ISSUE THREAD

**Issue by davidbgk** [DrkSephy/es6-cheatsheet#43]
Given the example chosen related to fetching a JSON, it might be interesting to mention [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) because it's exactly that use-case that it tries to solve. With promises :-)

**Comment by DrkSephy** [comment]
Will do, I actually have an example of using `fetch` that I've been meaning to put up. I'll get it up along with generators + promises.
