### ISSUE TITLE
WeakMaps example - Last line is effectively map.get(null);

### ISSUE THREAD

**Issue by reggieb** [DrkSephy/es6-cheatsheet#44]
In the WeakMaps section there is this example:

```
let map = new WeakMap();
let el  = document.getElementById('someElement');

// Store a weak reference to the element with a key
map.set(el, 'reference');

// Access the value of the element
let value = map.get(el); // 'reference'

// Remove the reference
el.parentNode.removeChild(el);
el = null;

value = map.get(el); // undefined
```

I am not sure what the last line is demonstrating. `el` has been set to `null` on the previous line, and wouldn't `map.get(null);` always return `undefined`

**Comment by DrkSephy** [comment]
As stated here:

> As shown above, once the object is is destroyed by the garbage collector, the WeakMap will automatically remove the key-value pair which was identified by that object.

And: 

> Note: To further illustrate the usefulness of this example, consider how jQuery stores a cache of objects corresponding to DOM elements which have references. Using WeakMaps, jQuery can automatically free up any memory that was associated with a particular DOM element once it has been removed from the document. In general, WeakMaps are very useful for any library that wraps DOM elements.

The idea is to show that the WeakMap value will be garbage collected once the object which it holds a reference to has been destroyed, effectively freeing up memory as these objects and their references are created/destroyed.

**Comment by reggieb** [comment]
Then I think this line should be removed:

```
el = null;
```

So that the example is:

```
let map = new WeakMap();
let el  = document.getElementById('someElement');

// Store a weak reference to the element with a key
map.set(el, 'reference');

// Access the value of the element
let value = map.get(el); // 'reference'

// Remove the reference
el.parentNode.removeChild(el);

value = map.get(el); // undefined
```
