### ISSUE TITLE
Best practices are too matter of factly stated

### ISSUE THREAD

**Issue by HamsterCoder** [DrkSephy/es6-cheatsheet#59]
Please provide references to discussions, articles, specs, etc. As of now, the only question that arises when I read best practices section is: "why"?

Why is block scope better than function scope (why not use var)?
Why should we replace every anonymous function with arrow function?

**Comment by DrkSephy** [comment]
These best practices come from reading other existing ES6 articles, exploring ES6 codebases and personal opinion. I never mentioned that `block scope` is better than function scope, nor did I mention that we should replace every anonymous function with arrow functions (only where we are simply using a callback or returning a simple expression). I'll be closing this now.

**Comment by HamsterCoder** [comment]
If you reread my issue I am asking to include the references, articles, etc. because stating best practices doesn't really have any value without references.

As to my questions I was referring to:

> Best Practice: Leave var declarations inside of legacy code to denote that it needs to be carefully refactored. When working on a new codebase, use let for variables that will change their value over time, and const for variables which cannot be reassigned.

Essentially encourages not to use var which in term means using block variable scope from now on, so why?

There are wonderful books that present best practices - Javascript Patterns, Javascript Good Parts,     Code Complete and they tend to explain every best practice they offer.
