### ISSUE TITLE
Easy example for ES5 .repeat()

### ISSUE THREAD

**Issue by sopilkar** [DrkSephy/es6-cheatsheet#65]
Instead of:

``` javascript
function repeat(string, count) {
    var strings = [];
    while(strings.length < count) {
        strings.push(string);
    }
    return strings.join('');
}
```

use easier example:

``` javascript

function repeat(string, count) {
    return new Array(count + 1).join(string);
}
```

**Comment by DrkSephy** [comment]
I'll keep the existing example, I wasn't looking for an easier example per say. Regardless, I only wanted to highlight the change from using `.repeat` to any other implementation of `repeat`. Thank you for your contribution!
