### ISSUE TITLE
add default values in destructuring

### ISSUE THREAD

**Issue by morenoh149** [DrkSephy/es6-cheatsheet#67]
did not find an example along the lines of

``` javascript
const foo = {a: 10}
let {a, b=20} = foo
console.log(a, b) // 10, 20
```

**Comment by DrkSephy** [comment]
Would you like to send in a pull request for this? Thanks!

**Comment by morenoh149** [comment]
documented elsewhere http://es6-features.org/#FailSoftDestructuring

**Comment by DrkSephy** [comment]
This feature is already present [here](https://github.com/DrkSephy/es6-cheatsheet#destructuring-objects).

**Comment by morenoh149** [comment]
not the default value aspect of destructuring. That example could be expanded so

``` javascript
var luke = { occupation: 'jedi', father: 'anakin' };
var occupation = luke.occupation; // 'jedi'
var father = luke.father; // 'anakin'

let luke = { occupation: 'jedi', father: 'anakin' };
let {occupation, father} = luke;

console.log(occupation); // 'jedi'
console.log(father); // 'anakin'

let {occupation="person", father, age=22} = luke
console.log(occupation); // 'jedi'
console.log(father); // 'anakin'
console.log(age); // 22
```

**Comment by DrkSephy** [comment]
It's covered [here](https://github.com/DrkSephy/es6-cheatsheet#named-parameters), sorry. It demonstrates that you can use destructuring for default params.

**Comment by morenoh149** [comment]
I saw that but felt it was only allowed when declaring parameters to a function. It's fine if we disagree on the clarity there.
