### ISSUE TITLE
Does Symbol.iterable method exist?

### ISSUE THREAD

**Issue by HyunSeob** [DrkSephy/es6-cheatsheet#73]
A paragraph written about `Symbol.iterable`

> A notable example of Symbol use for interoperability is `Symbol.iterable` which exists on all iterable and iterator types in ES6: Arrays, strings, generators, etc. When called as a method it returns an object with an Iterator interface.

I had been looking for `Symbol.iterable`. But, I can't find anything about `Symbol.iterable`.
I'm not sure.. But I think you just mistook `Symbol.iterator` with `Symbol.iterable`.

**Comment by DrkSephy** [comment]
It should be `Symbol.iterator`. Thank you!

**Comment by HyunSeob** [comment]
Good!
